#服务设置
Server:
  #占用IP
  Host: "0.0.0.0"
  #占用端口
  Port: 22332

#设置
Setting:
  #服务密码
  Password:
    #加密方式(base64/MD5/SHA256，推荐SHA256，不推荐base64)
    Encrypt: "SHA256"
    #密码
    Password: "C7806234B5A8590291323D3A3D9016ED65F33284BD546EB17E99F7BB4EF7D5A3"
  #数据缓存时间
  DataCacheTime: 600000
  #日期格式
  DateFormat: "yyyy/MM/dd-HH:mm:ss"
  #存储数据
  Data:
    #存储方式(SQLite/Mysql)
    Type: "MYSQL"
    Mysql:
      #地址
      Hostname: "jdbc:mysql://localhost"
      #端口
      Port: 3306
      #数据库
      Database: "authorize"
      #用户名
      Username: "root"
      #密码
      Password: "root"
      #重连次数
      ReconnectTime: 10
      #重连间隔(单位: 秒)
      ReconnectDelay: 3
    Sqlite:
      #存储位置
      Path: "/"
      File: "authorize.db"